version: '3.8'

services:
  # Serviço de desenvolvimento
  app-dev:
    build:
      context: .
      target: deps
    command: pnpm start
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - pnpm_cache:/root/.pnpm-store
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  # Serviço de produção
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_VERSION=${REACT_APP_VERSION:-1.0.0}
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  # Serviço Canary (para deploy sem downtime)
  app-canary:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_VERSION=${REACT_APP_VERSION:-canary}
    ports:
      - "3001:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production

volumes:
  pnpm_cache:
  node_modules: