apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-app
      version: stable
  template:
    metadata:
      labels:
        app: react-app
        version: stable
    spec:
      containers:
      - name: react-app
        image: ${REGISTRY}/react-app:stable
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
      version: canary
  template:
    metadata:
      labels:
        app: react-app
        version: canary
    spec:
      containers:
      - name: react-app
        image: ${REGISTRY}/react-app:canary
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"