name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

env:
  REGISTRY: api.magalu.cloud
  IMAGE_NAME: react-app
  MAGALU_REGION: br-se1
  API_URL: https://api.magalu.cloud/br-se1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Vamos pular a chamada da API por enquanto e focar no deploy da imagem
      - name: Configure Docker
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Magalu Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}/${{ env.MAGALU_REGION }}
          username: ${{ secrets.MAGALU_API_KEY }}
          password: ${{ secrets.MAGALU_API_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.MAGALU_REGION }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.MAGALU_REGION }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.MAGALU_REGION }}/${{ env.IMAGE_NAME }}:canary

      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Login no registry
            docker login ${{ env.REGISTRY }}/${{ env.MAGALU_REGION }} \
              -u ${{ secrets.MAGALU_API_KEY }} \
              -p ${{ secrets.MAGALU_API_KEY }}
            
            # Pull da nova imagem
            docker pull ${{ env.REGISTRY }}/${{ env.MAGALU_REGION }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            
            # Deploy canary (10% do tráfego)
            docker tag ${{ env.REGISTRY }}/${{ env.MAGALU_REGION }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
              ${{ env.REGISTRY }}/${{ env.MAGALU_REGION }}/${{ env.IMAGE_NAME }}:canary
            
            # Parar e remover container antigo se existir
            docker rm -f react-app-canary || true
            
            # Iniciar novo container
            docker run -d \
              --name react-app-canary \
              --restart unless-stopped \
              -p 3001:80 \
              ${{ env.REGISTRY }}/${{ env.MAGALU_REGION }}/${{ env.IMAGE_NAME }}:canary

      - name: Cleanup
        if: always()
        run: |
          docker logout ${{ env.REGISTRY }}/${{ env.MAGALU_REGION }}
