name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

env:
  REGISTRY: api.magalu.cloud
  IMAGE_NAME: react-app
  MAGALU_REGION: br-se1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Magalu Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}/${{ env.MAGALU_REGION }}
          username: ${{ secrets.MAGALU_API_KEY }}
          password: ${{ secrets.MAGALU_API_KEY }}
        env:
          DOCKER_CONFIG: $HOME/.docker
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.MAGALU_REGION }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.MAGALU_REGION }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login ${{ env.REGISTRY }}/${{ env.MAGALU_REGION }} -u ${{ secrets.MAGALU_API_KEY }} -p ${{ secrets.MAGALU_API_KEY }}
            docker pull ${{ env.REGISTRY }}/${{ env.MAGALU_REGION }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            bash /opt/app/deploy.sh ${{ env.REGISTRY }}/${{ env.MAGALU_REGION }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
