name: Canary Deployment

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

env:
  REGISTRY: api.magalu.cloud
  MAGALU_REGION: br-se1
  TF_VAR_api_key: ${{ secrets.MAGALU_API_KEY }}
  CANARY_WEIGHT: 20

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test -- --watchAll=false

  deploy-canary:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Configure Docker
        uses: docker/setup-buildx-action@v2

      - name: Create repository if not exists
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.MAGALU_API_KEY }}" \
            -H "Content-Type: application/json" \
            "https://${{ env.REGISTRY }}/v2/${{ env.MAGALU_REGION }}/repositories" \
            -d '{"name": "${{ github.repository }}"}'
        continue-on-error: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}:canary
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.sha }}
          build-args: |
            REACT_APP_VERSION=${{ github.sha }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        
      - name: Wait for deployment
        run: sleep 60  # Aguarda 1 minuto para a VM inicializar

      - name: Monitor Canary Health
        id: monitor
        run: |
          chmod +x ./monitor-canary.sh
          ./monitor-canary.sh
        
      - name: Rollback if Canary Unhealthy
        if: failure()
        run: |
          echo "Canary unhealthy, rolling back..."
          terraform destroy -target=module.app_canary -auto-approve

  promote-to-stable:
    needs: deploy-canary
    runs-on: ubuntu-latest
    steps:
      - name: Promote Canary to Stable
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.MAGALU_REGION }}/${{ env.IMAGE_NAME }}:stable

      # Aqui você pode adicionar steps para atualizar a versão stable
      # Por exemplo, atualizar um deployment do Kubernetes ou outra VM
