name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

env:
  REGISTRY: api.magalu.cloud
  IMAGE_NAME: react-app
  MAGALU_REGION: br-se1
  API_URL: https://api.magalu.cloud/br-se1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Primeiro, vamos obter informações da instância
      - name: Get Instance Info
        id: instance-info
        run: |
          INSTANCE_INFO=$(curl --location "${{ env.API_URL }}/compute/v1/instances" \
            --header "x-api-key: ${{ secrets.MAGALU_API_KEY }}" \
            --header "Accept: application/json")
          echo "instance_info=$INSTANCE_INFO" >> $GITHUB_OUTPUT
          
      - name: Configure Docker
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Magalu Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}/${{ env.MAGALU_REGION }}
          username: ${{ secrets.MAGALU_API_KEY }}
          password: ${{ secrets.MAGALU_API_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.MAGALU_REGION }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.MAGALU_REGION }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.MAGALU_REGION }}/${{ env.IMAGE_NAME }}:canary

      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Login no registry
            docker login ${{ env.REGISTRY }}/${{ env.MAGALU_REGION }} \
              -u ${{ secrets.MAGALU_API_KEY }} \
              -p ${{ secrets.MAGALU_API_KEY }}
            
            # Pull da nova imagem
            docker pull ${{ env.REGISTRY }}/${{ env.MAGALU_REGION }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            
            # Deploy canary (10% do tráfego)
            docker tag ${{ env.REGISTRY }}/${{ env.MAGALU_REGION }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
              ${{ env.REGISTRY }}/${{ env.MAGALU_REGION }}/${{ env.IMAGE_NAME }}:canary
            
            # Execute o script de deploy
            bash /opt/app/deploy.sh ${{ env.REGISTRY }}/${{ env.MAGALU_REGION }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Cleanup
        if: always()
        run: |
          docker logout ${{ env.REGISTRY }}/${{ env.MAGALU_REGION }}
